CREATE TABLE `patient` (
  `patientID` INT unsigned NOT NULL,
  `familyNameEn` varchar(30) NOT NULL,
  `firstNameEn` varchar(30) NOT NULL,
  `familyNameKh` varchar(30) NOT NULL,
  `firstNameKh` varchar(20) NOT NULL,
  `gender` char(1) NOT NULL,
  `dob` date NOT NULL,
  `nationality` char(2) NOT NULL,
  `caretakerNamekh` varchar(50) NOT NULL,
  `relationship` varchar(15) NOT NULL,
  `distance` varchar(20) NOT NULL,
  `provinceID` tinyint unsigned NOT NULL,
  `districtID` smallint unsigned NOT NULL,
  `communeID` smallint unsigned NOT NULL,
  `villageID` smallint unsigned NOT NULL,
  `address` varchar(200) DEFAULT NULL,
  `phone1` varchar(15) DEFAULT NULL,
  `phone2` varchar(15) DEFAULT NULL,
  `bloodGroup` char(4) DEFAULT NULL,
  `estimated_dob` char(1) NOT NULL DEFAULT 'N',
  `overAge` char(1) NOT NULL DEFAULT 'N',
  `deceased` char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`patientID`),
  CONSTRAINT `patient_commune` FOREIGN KEY (`communeID`) REFERENCES `commune` (`communeID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `patient_district` FOREIGN KEY (`districtID`) REFERENCES `district` (`districtID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `patient_province` FOREIGN KEY (`provinceID`) REFERENCES `province` (`provinceID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `patient_village` FOREIGN KEY (`villageID`) REFERENCES `village` (`villageID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

